### ISSUE TITLE
smart constructors for BExpr

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#589]
In the recent week I saw at least two cases that should be solved by smart constructors for BExpr:

In TxsHappy, we see the implementation of the smart constructor (that combines multiple parallels) in multiple places 
```
$$ = case $1 of
                        { Parallel chids bexps
                            -> if (Set.fromList chids) == (Set.fromList (chanIdExit:$$.inhChanSigs)
                                 then Parallel (chanIdExit:$$.inhChanSigs) (bexps ++ [$3])
                                 else Parallel (chanIdExit:$$.inhChanSigs) [$1,$3]
                        ; _ -> Parallel (chanIdExit:$$.inhChanSigs) [$1,$3]
                        }
```

For LPE, we want to replace the ActionPrefix `A[[False]] >-> P` by `STOP`

**Comment by pjljvandelaar** [comment]
- [x] Add smart constructors (indirection)  -- see #604
- [x] Add exception handling (checking e.g. guard has boolean valexpr) -> made separate issue #720
- [ ] Add smart constructor (logic)
  - [x] Stop
     - [x] No special Stop constructor, use Choice with empty list instead.
  - [x] Action Prefix
      - [x] A?x [[ False ]] >-> p == stop
  - [x] Guard
      - [x] [[ True ]] =>> p == p
      - [x] [[ False ]] =>> p == stop
      - [x] [[ c ]] =>> stop == stop
      - [x] [[ c1 ]] =>> A?x [[ True ]] >-> p == A?x [[ c1 ]] >-> p
      - [x] [[ c1 ]] =>> A?x [[ c2 ]] >-> p == A?x [[ IF c1 THEN c2 ELSE False FI ]] >-> p  -- prevent evaluation of c2 when c1 is false
      - [x] [[ c ]] =>> (p1 ## p2) == ( ([[ c ]] =>> p1)  ## ([[ c ]] =>> p2) )
  - [x] Choice
       - [x] Use set
       - [x] p ## stop == p    -- implied by set
       - [x] p ## p == p   --  implied by set
       - [x] (p ## q) ## r == p ## q ## r    -- nesting of choices can be flattened
  - [x] Parallel
      - [x] ~p |||  EXIT == p~
      - [x] ~Use multiset (see also #488)~ Not merged due to performance issues
      - [x] (p |[ G ]| q) |[ G ]| r == p |[ G ]| q |[ G ]| r    -- nesting of parallels over same channels can be flatten
  - [x] Enable
      - [x] stop >>> p == stop 
      - [x] ~not (Exit p1) => p1 >>> p2 == p1~ 
  - [x] Disable
     - [x] stop [>> p == p
     - [x] p [>> stop == p
  - [x] Interrupt
      - [x] p [>< stop == p
      - [x] ~stop [>< p = p+~ hardly used and considered too complex
              if `p` does not exit 
              then expression simplifies to `p`
              else since we lack the `+` operator for processes
              we could define `p' ::= p >>> p'` and replace `stop [>< p` by `p'`)
  - [x] ~ProcInst~
     - [x] When arguments are all values, replace by behavior of procdef
            Note: not always possible: recursive procdefs
            Loose LPE form
            Add test cases for `ANY`: a value that can't be used
  - [x] Hide
     - [x] Set of ChanIds (not a list, order is irrelevant)
  - [ ] ValueEnv
    - [ ] remove by using Subst
  - [x]  StAut - remove (see below)
  - [x] ISTEP
      - [x] ~P [G] (x) ::= p1 ## (ISTEP -> P [G] (x))    ==    P [G] (x) ::= p1~
             Should yield error message `divergence is undefined in ioco theory`
  - [x] subst
      - [x] subst Map.empty == id
   - [x] EXIT
       - [ ] EXIT [[ c ]] >-> p == EXIT [[ c ]] >-> STOP 
              Rewrite is currently problematic for LPE (#128).
              Also see remark in issue [#799](https://github.com/TorXakis/TorXakis/issues/799#issuecomment-444441710).
              Note: other rewrites of ActionPrefix still apply.
   - [x] ~bisimulation laws~ considered too complex to yield performance gain.
     - [x]  ISTEP >-> p ## p  ==  ISTEP >-> p
     - [x]  A >-> ISTEP >-> p  ==  A >-> p
     - [x]  A >-> ( p  ##  ISTEP >-> q )  ##  A >-> q   ==   A >-> ( p  ##  ISTEP >-> q )

**Comment by pjljvandelaar** [comment]
To rewrite the BExpr we have to specify the equivalence relation.

Possible rewrites
```
 p |[ X ]| EXIT == p
```
```
 p ## STOP == p
```
```
a [[False]] >-> p == STOP
```
Anything also used in LPE (see #128)

**Comment by pjljvandelaar** [comment]
See also #488 and #487

**Comment by pjljvandelaar** [comment]
- [x] Add StautDef to procdef translation:
  * Make a decision: do we use ANY or Maybe X?
  * Make a decision: do we require the initial state to be equal to 0 / zero? 
   - [x] 1. Create Procdef with 
       1. Same channel declarations
       2. Parameters:
          1. Starting with same parameters as StautDef
          2. add counter/StatId as parameter to procdef (type Int).
          3. Add global variables of StautDef as parameters to procdef (use same name + same type/ Maybe (same type))
  - [x] 2. Enumerated the states (zip [State] [0..])
  - [x] 3. Add one big choice and Replace `FromState -> Action [[Cond]] {update} -> ToState` by `Action [[ IF counter(FromState) THEN Cond ELSE False FI ]] >-> LET update IN procdef [ channels ] ( param, counter(ToState), global variables) NI`
  - [x] 4. Replace StautDef call/instantiation by ProcDef call with 
      1. Counter/StatId equal to initial state 
      2. Assignment of initial value to all global variables (use ANY/Nothing in case of no assignment)

**Comment by pjljvandelaar** [comment]
Alternative: add procdef that call stautdef with initial values. Use procInst to this procdef at all places where stautdef is instantiated.

**Comment by pjljvandelaar** [comment]
Implemented using the following choices: ANY and initial state can be any number.

**Comment by pjljvandelaar** [comment]
Possible improvement:
When `cond` is  `True`, don't generated `IF THEN ELSE FI` in
`alternative (Trans from' (ActOffer offers' cond) update' to')`
in StautDef.hs

This prevent code like observed with AdderStAut.txs:
```
( { Res ! statevar}
[[ ( IF ( 1 == $s ) THEN True ELSE False FI ) ]]
>-> ( std_adder [Act,Res] ( 0, statevar )
) )
```

alternative: solve it in the smart constructor of `ITE`

**Comment by pjljvandelaar** [comment]
With
`{-# LANGUAGE ViewPatterns #-}`
The following works:
```
alternative :: Trans -> BExpr
        alternative (Trans from' (ActOffer offers' (ValExpr.view -> Vconst (Cbool True)))  update' to') =
          let Just fromIndex = Map.lookup from' stateMap
              Just toIndex   = Map.lookup to'   stateMap in
            actionPref (ActOffer offers' (cstrEqual (cstrVar stateId) (cstrConst (Cint fromIndex))))
                       (procInst procId chans (combineArguments args' (cstrConst (Cint toIndex)) (map ( subst update' fdefs . cstrVar ) vars')))
        alternative (Trans from' (ActOffer offers' cond) update' to') =
          let Just fromIndex = Map.lookup from' stateMap
              Just toIndex   = Map.lookup to'   stateMap in
            actionPref (ActOffer offers' (cstrITE (cstrEqual (cstrVar stateId) (cstrConst (Cint fromIndex))) cond (cstrConst (Cbool False))))
                       (procInst procId chans (combineArguments args' (cstrConst (Cint toIndex)) (map ( subst update' fdefs . cstrVar ) vars')))
```

Any suggestion to reduce the code duplication?

**Comment by pjljvandelaar** [comment]
StAut not yet removed to keep supporting Petra van den Bos and her research to cover all states of a State Automaton.

**Comment by pjljvandelaar** [comment]
Also see #366 for a rewrite rule:
if procDef is just a procInst, replace procInst to that procDef by its procInst
this will save a procInst at run-time.
Note LPE (#128) already removes these procInst, so is low priority at most!

**Comment by pjljvandelaar** [comment]
When adding error handling to BExpr, one has another challenge.
For example, `Q` in the following context 
```
P1 ::= A?x >-> [[x>0]] ==> EXIT
Q ::= P1 >>> P2
```
is fine, since the `functionality` of P1 is `EXIT`.
However, once the action `A ! -3` is taken, substitution of `x` by `-3` will change `P1` into `STOP`.
The composition of `Q` has become invalid, since `>>>` requires that the initial process has `functionality` `EXIT` and `STOP` has functionality `NOEXIT`.

@tretmans Do you agree that since substitution is possible, one should not check on `functionality`, but only rewrite behaviour when possible. So rewrite `STOP >>> P2` to just `STOP` and don't throw an error?

**Comment by pjljvandelaar** [comment]
Alternative: check on creation, yet allow that due to substitution `functionality` can change and hence should no longer be checked.
