### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#620]

**Comment by pjljvandelaar** [comment]
Afterwards:
- [x] Move to latest LTS (unless there are known and relevant issues of the ghc version and/or used libraries) --> #649 
- [x] Move to latest Z3 version --> #643 
- [x] Move to latest CVC4 version (Do we still need development version?) --> #643 
- [ ] Add Yices (ONLY when issue is solved: https://github.com/SRI-CSL/yices2/issues/84) --> #265
- [x] Make an issue for next release with this content --> #652

**Comment by pjljvandelaar** [comment]
Make release more explicit: what has to be done
* Make windows installer
* Make bottles for homebrew
* ...

Include this information in issue for next release.

**Comment by pjljvandelaar** [comment]
@keremispirli you released 0.6.0
Shouldn't this issue be closed?

**Comment by pjljvandelaar** [comment]
Waiting on MacOS version...
