### ISSUE TITLE
Stack should build with the pedantic flag

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#91]
strategy:
- [x] Add -Werror to all cabal packages (ghc-options)
- [ ] Add -Wall to all files that have no warnings. I.e. add `{-# OPTIONS -Wall  #-}`.
- [ ] Add -Wall to all packages (ghc-options) when all files can be compiled with -Wall.
      Of course, remove the -Wall options field from all files in the package.

**Comment by keremispirli** [comment]
Pierre's proposal:
- [ ]  Add -Wall to all cabal packages (ghc-options) + Add GHC-OPTIONS pragma to files that contain warnings. This will serve as a safety net for future development.
- [ ] Make a new issue to remove all GHC-OPTIONS pragmas.

The remaining items in initial post won't be necessary anymore.
